name: Build Node binaries for Windows x86

on:
  workflow_dispatch:
  workflow_call:

jobs:
  windows-build:
    runs-on: windows-2022  # 替换弃用的 windows-2019

    strategy:
      fail-fast: false
      matrix:
        target-node: [18]
        target-arch: [x86]

    steps:
      - uses: actions/checkout@v4  # 升级到最新版

      - name: Use Node.js 14 (for building)
        uses: actions/setup-node@v4  # 升级到最新版
        with:
          node-version: 14
          architecture: x64  # 构建工具建议用64位

      - run: yarn install

      - run: choco install nasm -y  # 添加 -y 避免交互确认

      - name: Build Node binary
        run: yarn start --node-range node${{ matrix.target-node }} --arch ${{ matrix.target-arch }} --output dist

      - name: Verify binary
        id: verify_binary
        run: |
          $fileExists = Test-Path -Path dist\\*.sha256sum -PathType Leaf
          echo "exists=$fileExists" >> $GITHUB_OUTPUT
          if (-not $fileExists) { exit 1 }

      - uses: actions/upload-artifact@v4  # 升级到最新版
        if: steps.verify_binary.outputs.exists == 'true'
        with:
          name: node${{ matrix.target-node }}-windows-${{ matrix.target_arch }}
          path: dist/*
          retention-days: 7  # 可选：设置artifact保留时间
